<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;


//    protected function handleRecordCreation(array $data): Model
//    {
//
//        Log::info(json_encode($data));
//        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
//    }


}
