<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class EditOrder extends EditRecord
{
    protected static string $resource = OrderResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }

//    protected function handleRecordUpdate(Model $record, array $data): Model
//    {
//        Log::alert(json_encode($data));
//        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
//    }
}
